apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  # 'name' must match the filename of the manifest.
  name: snyk
spec:
  # 'version' is a valid semantic version string (see semver.org)
  version: "v0.0.1"
  # 'homepage' usually links to the GitHub repository of the plugin
  homepage: https://github.com/snyk/snyk
  # 'shortDescription' explains what the plugin does in only a few words
  shortDescription: "Scan images and manifests with Snyk"
  description: |
    Scans image and manifests with Snyk.
  # 'platforms' specify installation methods for various platforms (os/arch)
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
        - linux
    # 'uri' specifies .zip or .tar.gz archive URL of a plugin
    uri: https://github.com/snyk/snyk/archive/v1.420.1.tar.gz
    # 'sha256' is the sha256sum of the url above
    sha256: 
    # 'files' lists which files should be extracted out from downloaded archive
    files:
    - from: "snyk-linux"
      to: "./snyk"
    # 'bin' specifies the path to the the plugin executable among extracted files
    bin: snyk-linux

